ml py-pandas/2.2.2-63g5vk6

import pandas as pd

aa_word = 'WYFLIVMCAGPSTNQHRKDE'
env_aa = 'GLKRAMLSLIDGKGPIRFVLALLAFFRFTAIAPTRAVLDRWRGVNKQTAMKHLLSFKKELGTLTSAINRRSSKQKKRGGKTGIAVMIGLIASVGAVTLSNFQGKVMMTVNATDVTDVITIPTAAGKNLCIVRAMDVGYMCDDTITYECPVLSAGNDPEDIDCWCTKSAVYVRYGRCTKTRHSRRSRRSLTVQTHGESTLANKKGAWMDSTKATRYLVKTESWILRNPGYALVAAVIGWMLGSNTMQRVVFVVLLLLVAPAYSFNCLGMSNRDFLEGVSGATWVDLVLEGDSCVTIMSKDKPTIDVKMMNMEAANLAEVRSYCYLATVSDLSTKAACPTMGEAHNDKRADPAFVCRQGVVDRGWGNGCGLFGKGSIDTCAKFACSTKAIGRTILKENIKYEVAIFVHGPTTVESHGNYSTQVGATQAGRFSITPAAPSYTLKLGEYGEVTVDCEPRSGIDTNAYYVMTVGTKTFLVHREWFMDLNLPWSSAGSTVWRNRETLMEFEEPHATKQSVIALGSQEGALHQALAGAIPVEFSSNTVKLTSGHLKCRVKMEKLQLKGTTYGVCSKAFKFLGTPADTGHGTVVLELQYTGTDGPCKVPISSVASLNDLTPVGRLVTVNPFVSVATANAKVLIELEPPFGDSYIVVGRGEQQINHHWHKSGSSIGKAFTTTLKGAQRLAALGDTAWDFGSVGGVFTSVGKAVHQVFGGAFRSLFGGMSWITQGLLGALLLWMGINARDRSIALTFLAVGGVLLFLSVNVHADTGCAIDISRQELRCGSGV'
names=['InputPCR_WTNorm.tsv','DCSIGNR_P1_repA_WTNorm.tsv', 'DCSIGNR_P1_repB_WTNorm.tsv','C6-36_P1_repA_WTNorm.tsv', 'C6-36_P1_repB_WTNorm.tsv']

for num in range(0,5):
    P1_df = pd.read_csv(f'gatk/{num}.aaCounts', delimiter='\t')
    f = open(f'enrichIn/{names[num]}', 'w')
    f.write('hgvs\tcount\n')
    for i in range(782):
        temp_aa = P1_df.iloc[i]
        for aa in aa_word:
            if aa != env_aa[i]:
                new_word = 'p.(' + env_aa[i] + str(i+1) + aa + ')\t' + str(temp_aa[aa]) + '\n'
                f.write(new_word)
            else:
                new_word = 'p.(' + env_aa[i] + str(i+1) + aa + ')\t' + str(0) + '\n'
                f.write(new_word)
    f.close()
